#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -lpthread
OBJDIR_DEBUG = obj
DEP_DEBUG = 
OUT_DEBUG = app/Maze

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/maze.o $(OBJDIR_DEBUG)/maze_solver.o $(OBJDIR_DEBUG)/thread.o

all: debug

clean: clean_debug

before_debug: 
	test -d app/ || mkdir -p app/
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/maze.o: maze.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c maze.c -o $(OBJDIR_DEBUG)/maze.o

$(OBJDIR_DEBUG)/maze_solver.o: maze_solver.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c maze_solver.c -o $(OBJDIR_DEBUG)/maze_solver.o

$(OBJDIR_DEBUG)/thread.o: thread.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c thread.c -o $(OBJDIR_DEBUG)/thread.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf app
	rm -rf $(OBJDIR_DEBUG)

.PHONY: before_debug after_debug clean_debug

